// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"w-full px-6 py-4 flex items-center justify-between bg-red-200 dark:bg-gray-950 border-b border-gray-200 dark:border-gray-800\"><a href=\"/\" class=\"flex items-center gap-2 text-emerald-400\"><svg xmlns=\"http://www.w3.org/2000/svg\" attr:viewBox=\"0 0 40 40\" width=\"62\" height=\"42\" fill=\"none\"><rect x=\"4\" y=\"12\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect> <rect x=\"14\" y=\"2\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect> <rect x=\"24\" y=\"12\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect> <rect x=\"34\" y=\"2\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect> <rect x=\"44\" y=\"12\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect></svg></a><div class=\"flex items-center gap-1 text-xs font-semibold\"><a href=\"#about\" class=\"rounded-full px-4 py-2 transition-colors hover:bg-white/80 hover:text-gray-900 dark:hover:bg-white/10\">About</a> <a href=\"#experience\" class=\"rounded-full px-4 py-2 transition-colors hover:bg-white/80 hover:text-gray-900 dark:hover:bg-white/10\">Experience</a> <a href=\"#highlights\" class=\"rounded-full px-4 py-2 transition-colors hover:bg-white/80 hover:text-gray-900 dark:hover:bg-white/10\">Highlights</a> <a href=\"#skills\" class=\"rounded-full px-4 py-2 transition-colors hover:bg-white/80 hover:text-gray-900 dark:hover:bg-white/10\">Skills</a> <a href=\"#credentials\" class=\"rounded-full px-4 py-2 transition-colors hover:bg-white/80 hover:text-gray-900 dark:hover:bg-white/10\">Credentials</a> <a href=\"#contact\" class=\"rounded-full border border-gray-900/20 px-4 py-2 transition-colors hover:bg-gray-900 hover:text-white dark:border-white/30 dark:hover:bg-white dark:hover:text-gray-900\">Contact</a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
