// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"fixed top-0 inset-x-0 z-50 transition-all duration-300 w-full px-6 py-4 flex items-center justify-between border-b border-gray-200 dark:border-gray-800 backdrop-blur-lg bg-transparent\"><a href=\"/\" class=\"flex items-center gap-2 text-emerald-400\"><svg xmlns=\"http://www.w3.org/2000/svg\" attr:viewBox=\"0 0 40 40\" width=\"62\" height=\"42\" fill=\"none\"><rect x=\"4\" y=\"12\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect> <rect x=\"14\" y=\"2\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect> <rect x=\"24\" y=\"12\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect> <rect x=\"34\" y=\"2\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect> <rect x=\"44\" y=\"12\" width=\"14\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"3\"></rect></svg><h2 class=\"text-xl font-semibold text-emerald-500 uppercase tracking-[0.3em]\">BITGUARD</h2></a><div class=\"p-0\"><a class=\"inline-flex items-center gap-2 rounded-full bg-emerald-500 px-6 py-3 text-sm font-semibold uppercase tracking-wide text-white shadow-lg shadow-emerald-500/40 transition hover:-translate-y-0.5 hover:bg-emerald-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-300\">Get a Quote <svg class=\"h-4 w-4\" viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M5 12h14M13 6l6 6-6 6\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path></svg></a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
